[book]
authors = ["貴島"]
language = "ja"
multilingual = false
src = "src"
title = "📜 ORiguchi Documents"

[output.html]
additional-css = ["mdbook.css"]

[preprocessor.toc]
command = "mdbook-toc"
renderer = ["html"]
