services:
  or-server:
    build:
      context: .
      target: app
    container_name: or-server
    ports:
      - "8008:3000"
    volumes:
      - ./:/work
    working_dir: /work
    restart: always
    command: bash -c "mdbook serve -p 3000 -n 0.0.0.0"
    labels:
      description: "郷土資料"
